### ISSUE TITLE
打卡失败

### ISSUE THREAD

**Issue by marigold233** [XiaoMiku01/JUEJIN-FRIENDS-21days#1]
有个账号能成功

log：
```text
[root@VM-0-9-centos JUEJIN-FRIENDS-21days]# python3 main.py
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/root/python-scipts/JUEJIN-FRIENDS-21days/main.py", line 289, in <module>
    day()  # 启动时先打卡一次
  File "/root/python-scipts/JUEJIN-FRIENDS-21days/main.py", line 261, in day
    "pic_list": uploadImage(cookie),
  File "/root/python-scipts/JUEJIN-FRIENDS-21days/main.py", line 141, in uploadImage
    e = get_token(cookie)
  File "/root/python-scipts/JUEJIN-FRIENDS-21days/main.py", line 123, in get_token
    logging.error("获取token失败", r.text)
Message: '获取token失败'
Arguments: ('{"err_no":403,"err_msg":"权限认证错误","data":null}',)
2022-11-19 10:58:46,401 - main.py[line:143] - ERROR: 获取token失败
2022-11-19 10:58:46,534 - main.py[line:272] - ERROR: day1 打卡失败 {"err_no":403,"err_msg":"must bind phone","data":null}
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/root/python-scipts/JUEJIN-FRIENDS-21days/main.py", line 289, in <module>
    day()  # 启动时先打卡一次
  File "/root/python-scipts/JUEJIN-FRIENDS-21days/main.py", line 261, in day
    "pic_list": uploadImage(cookie),
  File "/root/python-scipts/JUEJIN-FRIENDS-21days/main.py", line 141, in uploadImage
    e = get_token(cookie)
  File "/root/python-scipts/JUEJIN-FRIENDS-21days/main.py", line 123, in get_token
    logging.error("获取token失败", r.text)
Message: '获取token失败'
Arguments: ('{"err_no":403,"err_msg":"权限认证错误","data":null}',)
2022-11-19 10:58:51,836 - main.py[line:143] - ERROR: 获取token失败
2022-11-19 10:58:51,996 - main.py[line:272] - ERROR: day1 打卡失败 {"err_no":403,"err_msg":"must bind phone","data":null}
/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.asoulfanart.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2022-11-19 10:59:04,244 - main.py[line:270] - INFO: day1 打卡成功
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/root/python-scipts/JUEJIN-FRIENDS-21days/main.py", line 289, in <module>
    day()  # 启动时先打卡一次
  File "/root/python-scipts/JUEJIN-FRIENDS-21days/main.py", line 261, in day
    "pic_list": uploadImage(cookie),
  File "/root/python-scipts/JUEJIN-FRIENDS-21days/main.py", line 141, in uploadImage
    e = get_token(cookie)
  File "/root/python-scipts/JUEJIN-FRIENDS-21days/main.py", line 123, in get_token
    logging.error("获取token失败", r.text)
Message: '获取token失败'
Arguments: ('{"err_no":403,"err_msg":"权限认证错误","data":null}',)
2022-11-19 10:59:09,508 - main.py[line:143] - ERROR: 获取token失败
2022-11-19 10:59:09,701 - main.py[line:272] - ERROR: day1 打卡失败 {"err_no":403,"err_msg":"must bind phone","data":null}
```

**Comment by XiaoMiku01** [comment]
cookie没拿全

**Comment by marigold233** [comment]
cookie抓全，还会有账号失败
```text
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/root/python-scipts/JUEJIN-FRIENDS-21days/main.py", line 295, in <module>
    day()  # 启动时先打卡一次
  File "/root/python-scipts/JUEJIN-FRIENDS-21days/main.py", line 267, in day
    "pic_list": uploadImage(cookie),
  File "/root/python-scipts/JUEJIN-FRIENDS-21days/main.py", line 147, in uploadImage
    e = get_token(cookie)
  File "/root/python-scipts/JUEJIN-FRIENDS-21days/main.py", line 129, in get_token
    logging.error("获取token失败", r.text)
Message: '获取token失败'
Arguments: ('{"err_no":403,"err_msg":"权限认证错误","data":null}',)
2022-11-20 10:49:34,137 - main.py[line:149] - ERROR: 获取token失败
2022-11-20 10:49:34,273 - main.py[line:278] - ERROR: day1 打卡失败 {"err_no":403,"err_msg":"must bind phone","data":null}
```
